sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ivanchen
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHuyspfQFNAAG1fd4W7
    access-key-secret: gD6DDguUhz50Ls066DMiMHVJfgvrJY
    bucket-name: cloud-tool-ivan
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10