sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ivanchen
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHuyspfQFNAAG1fd4W7
    access-key-secret: gD6DDguUhz50Ls066DMiMHVJfgvrJY
    bucket-name: cloud-tool-ivan
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxe896f9e7cd8a8445
    secret: 73f51a500a42fa2f06532002fce6946f
    mchid: 1561414331
    mch-serial-no: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url: https://7907d7f0.r7.vip.cpolar.cn/notify/paySuccess
    refund-notify-url: https://7907d7f0.r7.vip.cpolar.cn/notify/refundSuccess
  shop:
    address: 海口市龙华区金龙路2号
  baidu:
    ak: wCKAm6QUA1PzgaeY1w0YOSjXws6C9AAD